# Generated by Django 5.1.5 on 2025-02-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='objects_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
