# Generated by Django 5.1.5 on 2025-02-01 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('user_api', '0002_alter_user_details_objects_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content_type'),
        ),
    ]
